crowdfunder/config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  root 'projects#index'

  resources :user_sessions, only: [:create, :destroy]
  resources :users

  resources :projects do
    resources :rewards do
      resources :pledges, only: [:create, :destroy]
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

crowdfunder/app/models/pledge.rb
class Pledge < ActiveRecord::Base
  has_one :project, through: :reward
  belongs_to :reward
  belongs_to :user
end

crowdfunder/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :pledges, through: :rewards
  has_many :backers, class_name: 'User', through: :pledges
  belongs_to :owner, class_name: 'User'
end

crowdfunder/app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :pledges
  has_many :users, through: :pledges
end

crowdfunder/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :pledges
  has_many :rewards, through: :pledges
  has_many :owned_projects, class_name: 'Project', source: "owner"
  has_many :backed_projects, class_name: 'Project', through: :pledges, source: "project"


  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

crowdfunder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

crowdfunder/app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  def create

    # create the pledge
    Pledge.create( {user_id: params[:user_id], reward_id: params[:reward_id]} )

    # decrement the reward count
    r = Reward.find(params[:reward_id]).update_column
    r.update_column(:amount, r.amount-1)

    redirect_to project_path(params[:project_id])
  end

end

crowdfunder/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    @project.user_id = current_user.id

    if @project.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :funding_goal, :start_date, :end_date, :category)
  end

end

crowdfunder/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # def new

  # end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'Logged out!')
  end
end

crowdfunder/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_back_or_to root_url, :notice => "Signed up!"
    else
      render :new, :notice => "Try again"
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

crowdfunder/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdfunder/app/helpers/pledges_helper.rb
module PledgesHelper
end

crowdfunder/app/helpers/projects_helper.rb
module ProjectsHelper
end

crowdfunder/app/helpers/user_helper.rb
module UserHelper
end

crowdfunder/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

crowdfunder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="nav">
  <% if current_user %>
    <%= link_to "Logout", :logout, method: :post %>
    <%= link_to "My page", user_path(current_user) %>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", :login %>
  <% end %>
</div>
<div>
  <p id="notice"><%= flash[:notice] %></p>
  <p id="alert"><%= flash[:alert] %></p>
</div>

<%= yield %>

</body>
</html>

crowdfunder/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <div class ="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class ="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class ="field">
    <%= f.label :funding_goal %><br />
    <%= f.number_field :funding_goal %>
  </div>

  <div class ="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>

    <div class ="field">
    <%= f.label :start_date %><br />
    <%= f.date_field :start_date%>

  <div class ="field">
    <%= f.label :end_date %><br />
    <%= f.date_field :end_date%>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

crowdfunder/app/views/projects/index.html.erb
<h1>All Projects</h1>

<ul>
  <% @projects.each do |p| %>
    <li>
      <%= p.name %>
      <%= p.description %>
      <%= p.funding_goal %>
      <%= p.start_date %>
      <%= p.end_date %>
      <%= p.category %>
      <%= link_to 'See project', project_path(p) %>
    </li>
  <% end %>
</ul>

crowdfunder/app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

<%= link_to 'Back', projects_path %>

crowdfunder/app/views/projects/show.html.erb
<h1>Project: <%= @project.name %></h1>
<p>Description: <%= @project.description %></p>
<p>Funding Goal: <%= @project.funding_goal %></p>
<p>Start Date: <%= @project.start_date %></p>
<p>End Date: <%= @project.end_date %></p>
<p>Category: <%= @project.category %></p>

<h2> Rewards </h2>

<% @project.rewards.each do |r| %>
  <h4><em><%= r.name %></em>
    <%= button_to 'Back me!', project_reward_pledges_path(user_id: current_user.id, reward_id: r.id, project_id: @project.id) %>
  </h4>
  <p>Description: <%= r.description %></p>
  <p>Amount: <%= r.amount %></p>
  <p>Availability: <%= r.availability %></p>



<% end %>

crowdfunder/app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

crowdfunder/app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

crowdfunder/app/views/users/_form.html.erb
<div>
  <%= form_for @user do |f| %>

    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
       <%= f.label :first_name %><br />
       <%= f.text_field :first_name %>
    </div>
    <div class="field">
       <%= f.label :last_name %><br />
       <%= f.text_field :last_name %>
    </div>
    <div class="field">
       <%= f.label :email %><br />
       <%= f.text_field :email %>
    </div>
    <div class="field">
       <%= f.label :password %><br />
       <%= f.password_field :password %>
    </div>
    <div class="field">
       <%= f.label :password_confirmation %><br />
       <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit class: 'input'%></div>

  <% end %>

</div>

crowdfunder/app/views/users/new.html.erb
<h1>Create user</h1>

<%= render 'form' %>

<%= link_to 'Back', "/" %>

crowdfunder/app/views/users/show.html.erb
<h1>
  <%= "Hi #{@user.first_name} #{@user.last_name}" %>
</h1>

<%= link_to("Create Project", new_project_path) %>

<h2>Owned projects</h2>

<ul>
  <%= @user.owned_projects.each do |p| %>
    <li><%= "#{p.name}, #{p.description}, #{p.funding_goal}, #{p.start_date}, #{p.end_date}" %></li>
  <% end %>
</ul>